### ISSUE TITLE
Remove SRS drop down menu from portal

### ISSUE THREAD

**Issue by KoalaGeo** [OneGeology/OneGeology_Portal#6]
Believe it has limited use for users. 

Could be replaced with base map drop down - more common in data portals

**Comment by KoalaGeo** [comment]
Just having a play to see how the issue tracker works with a couple of examples and if it's something we might like to use.

**Comment by nmtoken** [comment]
Agree it probably has limited use, but we were asked to add it by OneGeology members.   A base map drop down and different CRS are different issues.
