### ISSUE TITLE
Update documentation link

### ISSUE THREAD

**Issue by KoalaGeo** [OneGeology/OneGeology_Portal#9]
In the help tab update documentation link to 

https://onegeology.github.io/documentation/ 

Will depreciate readthedocs build.

**Comment by nmtoken** [comment]
In https://onegeology.github.io/documentation/providingdata.html#onegeology-profile

There is a hard link to Appendix I ~ https://onegeology.github.io/wmsCookbook/appendixI.html.  
Deprecating is OK, but check no hard links prior to removal. 

Link is now broken, and there is no corresponding link at https://onegeology.github.io/documentation/appendixI.html 

I note that there is: https://onegeology.github.io/documentation/appendices.html  

_appendices_ suggests many there are many in the original documentation, but only one here.  I think K  is elsewhere (origainal at http://www.onegeology.org/wmsCookbook/appendixK.html).  What about L?

Probably would be worth also listing some full GetCap responses like http://www.onegeology.org/wmsCookbook/appendixF.html

**Comment by KoalaGeo** [comment]
The whole thing needs going over in truth. All the content was copied over, so is in there but various headings and links to them need to be looked at.

**Comment by nmtoken** [comment]
What does all copied over... mean here? 

Does it mean that all Cookbook content that was on the web site (http://www.onegeology.org/wmsCookbook) has been copied over to https://onegeology.github.io/documentation (or the underlying repo)?

Related, but also I think we seem to be going back to having monolithic pages, when what we envisaged was lots of smaller pages.  It's getting difficult to find stuff...

**Comment by KoalaGeo** [comment]
Yes everything at http://www.onegeology.org/wmsCookbook (+ some of the older HTML pages which didn't have rst files) is in https://github.com/OneGeology/documentation (https://onegeology.github.io/documentation is built from the master branch using github actions each time there's a commit) 

I did copy/merge things into larger files which I found easier to manage at the time, however in hindsight I see the benefit of more bitesize rst's...

There’s a couple of pages which could be moved but I haven’t and are open to discussion. 
http://www.onegeology.org/technical_progress/esriGrantOffer.html
http://www.onegeology.org/technical_progress/accreditationForm.cfm

Updates are still required to reflect the latest portal release, some work needed on heading hierarchies and checking links but it is functional and useable in current state.  

Pages which have had content copied to https://github.com/OneGeology/documentation  

- http://onegeology.org/technical_progress/
- http://onegeology.org/technical_progress/technical.html
- http://onegeology.org/technical_progress/buddy_home.html
- http://www.onegeology.org/technical_progress/geosciml.html
- http://www.onegeology.org/service_provision/home.html
- http://www.onegeology.org/service_provision/service_types.html
- http://www.onegeology.org/service_provision/data_formats.html
- http://www.onegeology.org/service_provision/data_content.html
- http://www.onegeology.org/service_provision/data_preparation.html
- http://www.onegeology.org/service_provision/data_preparation/paper_map.html
- http://www.onegeology.org/service_provision/data_preparation/lite.html
- http://www.onegeology.org/service_provision/data_preparation/complex.html

- http://www.onegeology.org/service_provision/onegeology_profile.html
- http://www.onegeology.org/service_provision/server_setup.html
- http://www.onegeology.org/service_provision/server_setup/exampledata.html
- http://www.onegeology.org/service_provision/server_setup/geoserver.html
- http://www.onegeology.org/service_provision/server_setup/mapserver.html
- http://www.onegeology.org/service_provision/server_setup/esri.html
- http://www.onegeology.org/service_provision/server_setup/apacheproxy.html
- http://www.onegeology.org/use/home.html
- http://www.onegeology.org/use/portal.html
- http://www.onegeology.org/use/portal/view_registered.html
- http://www.onegeology.org/use/portal/view_external.html
- http://www.onegeology.org/use/portal/kml.html
- http://www.onegeology.org/use/portal/wmc.html
- http://www.onegeology.org/use/portal/thematic_analysis.html
- http://www.onegeology.org/use/qgis.html
- http://www.onegeology.org/use/esri.html


- Everything under - http://www.onegeology.org/wmsCookbook/home.html

- Old HTML Cookbook

- http://www.onegeology.org/portal/portal_uses.html
- http://www.onegeology.org/portal/usage_guidance.html
- http://www.onegeology.org/howto/home.html
- http://www.onegeology.org/howto/1_4_1_1.html
- http://www.onegeology.org/howto/1_4_2.html
- http://www.onegeology.org/howto/1_4_3_1.html
- http://www.onegeology.org/howto/1_4_3_2.html
- http://www.onegeology.org/howto/1_4_4.html
- http://www.onegeology.org/howto/1_4_5.html
- http://www.onegeology.org/howto/1_4_6.html
- http://www.onegeology.org/howto/1_4_7.html
- http://www.onegeology.org/howto/1_4_8.html

**Comment by nmtoken** [comment]
> •	Everything under - http://www.onegeology.org/wmsCookbook/home.html

Where is http://www.onegeology.org/wmsCookbook/appendixA.html to http://www.onegeology.org/wmsCookbook/appendixL_1.html   

Not all content is now relevant but most needs to exist in the documentation somewhere.

**Comment by nmtoken** [comment]
ESRI grant offer is not cookbook material, so shouldn't move.

Accreditation possibly could be copied (it's static) when discussing validation but the page on the web site is a form (application) so needs to stay.

**Comment by KoalaGeo** [comment]
> 
> Where is http://www.onegeology.org/wmsCookbook/appendixA.html to http://www.onegeology.org/wmsCookbook/appendixL_1.html
> 
> Not all content is now relevant but most needs to exist in the documentation somewhere.

I see what's happened. So everything in https://kwvmxgit.ad.nerc.ac.uk/geowebservices/1gCookbook was taken over, but some of the html only pages (the appendices) were missed as they're not in the repo. 

Appendices:

* A
* B
* C
* D
* E
* F (done)
* G
* H
* I (done)
* J
* K (done)
* L

**Comment by KoalaGeo** [comment]
Extracted all the html pages (including images) to rst using pandoc. 

https://github.com/OneGeology/documentation/tree/master/docs/appendices 

Need tidying and alot of the header info removed before they go into main documentaion.

**Comment by KoalaGeo** [comment]
Changed appendices file to include toc, refering to the seperate appendix files so now live. 

Files need headers/footers removing

**Comment by nmtoken** [comment]
This brings a point up about style.  At least one appendix (L?) uses a style from the old OneGeology Europe pages.  Blue/green... Ideally this needs to kept in the cookbook pages,  it's in a css file in the headers at the moment, how can this be transferred.  

I noticed too in the ERML lite pages,  we use colour to delineate content  lines in the tables, to make it more readable, but in the current GitHub pages here's no colour.   How do we keep the colours, or incorporate style more generally.

**Comment by KoalaGeo** [comment]
I'll try and use http://tabulator.info/examples/4.5 which should work in a html block....

**Comment by bgsmase** [comment]
This issue has strayed from the original problem of updating the link in the Portal help tab into a general one on new cookbook structure which belongs in the documentation project if any of it is still relevant. Closing this issue and creating a new one just to address the link from the Portal to the documentation.
